### ISSUE TITLE
Stripping/ignoring unwanted fields

### ISSUE THREAD

**Issue by tnrich** [bogus34/bookshelf-fields#8]
Hey there,

I was wondering if this library provided a way to strip unwanted fields?

Say in my post method I have

```
new Book(req.body).save()
```

but the req.body has several fields that I don't want to actually save to the database. Does your plugin provide a way of stripping those fields upon creation or saving of the Book instance?

Thanks so much!

**Comment by bogus34** [comment]
No, you should sanitize request before applying to model.
